name: Workspace

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - v*

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-08-12
          targets: x86_64-unknown-linux-gnu
          components: clippy, rustfmt
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-x86_64-unknown-linux-gnu
          restore-keys: ${{ runner.os }}-cargo-
      #      TODO: Fix compilation failing due to a misconfigured compilation targets:
      #      Did you forget to enable `atomics` and `bulk-memory` features as outlined in wasm-bindgen-rayon README?
      #      - run: cargo clippy --all --all-features -- -D warnings
      - run: cargo clippy --all -- -D warnings
      - run: cargo fmt --all -- --check
      - name: Install cargo-machete
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-machete
      - run: cargo machete --with-metadata
      # TODO: Fails to install on current nightly, find an older crate version or consider bumping the nightly version
      #      - name: Install cargo-sort
      #        uses: baptiste0928/cargo-install@v1
      #        with:
      #          crate: cargo-sort
      #      - run: cargo sort --check
      - run: cargo test --release

# TODO: Failing due to WASM test compilation issues:
# | error[E0658]: use of unstable library feature 'stdsimd'
# |   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-futures-0.4.42/src/task/multithread.rs:38:13
#  wasm-pack-test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: dtolnay/rust-toolchain@v1
#        with:
#          toolchain: nightly-2023-08-12
#          targets: wasm32-unknown-unknown
#      - uses: actions/cache@v3
#        continue-on-error: false
#        with:
#          path: |
#            ~/.cargo/bin/
#            ~/.cargo/registry/index/
#            ~/.cargo/registry/cache/
#            ~/.cargo/git/db/
#            target/
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#          restore-keys: ${{ runner.os }}-cargo-
#      - name: Add Rust source component (`rust-src`)
#        run: rustup component add rust-src
#      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
#      - run: |
#          export RUSTFLAGS="-C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-arg=--max-memory=4294967296"
#          export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS=$RUSTFLAGS
#          wasm-pack test --node
#        working-directory: shielder-wasm
  
  wasm-ts-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-08-12
          targets: wasm32-unknown-unknown
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-wasm32-unknown-unknown
          restore-keys: ${{ runner.os }}-cargo-
        # TODO: Always install a pinned wasm-pack version, everywhere
      - name: Add Rust source component (`rust-src`)
        run: rustup component add rust-src
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: |
          export RUSTFLAGS="-C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-arg=--max-memory=4294967296"
          export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS=$RUSTFLAGS
          ./scripts/build.bash nodejs
        working-directory: shielder-wasm
      # TODO: Enable after adding tests etc.
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: --cwd shielder-wasm/examples/node install
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: --cwd shielder-wasm/examples/node build
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: --cwd shielder-wasm/examples/node test

  test-ts:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-08-12
          targets: wasm32-unknown-unknown
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-wasm32-unknown-unknown
      - name: Add Rust source component (`rust-src`)
        run: rustup component add rust-src
      # Need to build WASM first, then the extension
      # TODO: Always install a pinned wasm-pack version, everywhere
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: |
          export RUSTFLAGS="-C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-arg=--max-memory=4294967296"
          export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS=$RUSTFLAGS
          ./scripts/build.bash web
        working-directory: shielder-wasm
      # TODO: Implement pnpm caching in other places too
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
          run_install: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: shielder-ts/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: shielder-ts
      - run: pnpm lint
        working-directory: shielder-ts
      - run: pnpm build
        working-directory: shielder-ts
      - run: pnpm test
        working-directory: shielder-ts

  codecov:
    runs-on: ubuntu-latest
    needs: [ rust-test ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "nightly-2023-08-12"
          targets: x86_64-unknown-linux-gnu
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-x86_64-unknown-linux-gnu
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      # Only checking the coverage of the main library,
      # bindings are covered by their language's tests.
      - name: Generate code coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --no-default-features
      # TODO: Also upload the coverage of the pnpm workspace after setting up tests with coverage
      - name: Upload Rust coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: piotr-roslaniec/crispy-waffle

  # TODO: Just compiling benchmarks for now
  compile-benchmarks:
    runs-on: ubuntu-latest
    needs: [ rust-test ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "nightly-2023-08-12"
          targets: x86_64-unknown-linux-gnu
      - name: Compile benchmarks
        run: cargo bench --no-run --no-default-features
