name: Workspace

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - v*

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          # TODO: What is our target toolchain?
          #toolchain: stable
          toolchain: "nightly-2023-08-12"
          components: clippy, rustfmt
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo clippy --all --all-features -- -D warnings
      - run: cargo fmt --all -- --check
      - name: Install cargo-machete
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-machete
      - run: cargo machete
      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-sort
      - run: cargo sort --check

  rust-test:
    runs-on: ubuntu-latest
    needs: [ check ]
    strategy:
      matrix:
        include:
          # TODO: We don't have to worry about MSRV just yet
          # TODO: Track and enforce MSRV
          # - target: x86_64-unknown-linux-gnu
          #   rust: 1.67 # MSRV, `cargo msrv`
          - target: x86_64-unknown-linux-gnu
            rust: stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo check --all-features
      - run: cargo test --release

  wasm-pack-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          # TODO: We don't have to worry about that just yet
          # - 1.67 # MSRV
          - stable
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --node
        working-directory: shielder-wasm
  
  wasm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build --target nodejs
        working-directory: shielder-wasm
      # TODO: Enable after adding tests etc.
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: --cwd shielder-wasm/examples/node install
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: --cwd shielder-wasm/examples/node build
      # - uses: borales/actions-yarn@v3.0.0
      #   with:
      #     cmd: --cwd shielder-wasm/examples/node test

  build-extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh # TODO: Always use pinned version
      - run: wasm-pack build --target nodejs
      - name: Cache pnpm modules # TODO: Implement caching in other places
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 16.x # TODO: Switch to 18.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build
        working-directory: shielder-extension

  codecov:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      # Only checking the coverage of the main library,
      # bindings are covered by their language's tests.
      - name: Generate code coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --no-default-features
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true

  # TODO: Just compiling benchmarks for now
  compile-benchmarks:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - name: Compile benchmarks
        run: cargo bench --no-run --no-default-features
